repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
    - id: autoflake
      args: [
        '--in-place',
        '--remove-unused-variable',
        '--remove-all-unused-imports',
        ]

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black
    args: ['--line-length=88']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ['--max-line-length=88']
